source "https://rubygems.org"

gem "rails", "~> 7.2.1"
gem "pg", "~> 1.1"
gem "puma", ">= 5.0"
gem "tzinfo-data", platforms: %i[ windows jruby ]
gem "bootsnap", require: false
gem "rack-cors"
gem "devise"
gem "devise-jwt"
gem "faker"
gem "groupdate"
gem 'kaminari'

group :development, :test do
  gem "debug", platforms: %i[ mri windows ]
  gem "rspec-rails"
  gem "factory_bot_rails"
  gem "rubocop", require: false
end

group :test do
  gem "shoulda-matchers"
  gem "database_cleaner-active_record"
end